// Build script to generate config.js with environment variables
const fs = require('fs');

// Get environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

// Log what we found (without exposing the full key)
console.log('Building config.js...');
console.log('NEXT_PUBLIC_SUPABASE_URL:', supabaseUrl ? '✅ Found' : '❌ Missing');
console.log('NEXT_PUBLIC_SUPABASE_ANON_KEY:', supabaseAnonKey ? '✅ Found' : '❌ Missing');

const config = `// Supabase Configuration - Generated at build time
// DO NOT EDIT THIS FILE MANUALLY - Edit build-config.js instead

window.ENV = {
  SUPABASE_URL: '${supabaseUrl}',
  SUPABASE_ANON_KEY: '${supabaseAnonKey}'
};

// Validation: Check if environment variables were properly set
if (!window.ENV.SUPABASE_URL || !window.ENV.SUPABASE_ANON_KEY) {
  console.error('❌ Supabase environment variables not configured!');
  console.error('Please add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to your Vercel project settings.');
  console.error('See SUPABASE_SETUP.md for instructions.');
}
`;

fs.writeFileSync('config.js', config);
console.log('✅ config.js generated successfully');

// Exit with error if env vars are missing
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('\n⚠️  WARNING: Missing environment variables!');
  console.error('The build will continue, but the site will not work correctly.');
  console.error('Please add the environment variables in Vercel project settings.');
}
