// Build script to generate config.js with environment variables
const fs = require('fs');

const config = `// Supabase Configuration - Generated at build time
// DO NOT EDIT THIS FILE MANUALLY - Edit build-config.js instead

window.ENV = {
  SUPABASE_URL: '${process.env.NEXT_PUBLIC_SUPABASE_URL || ''}',
  SUPABASE_ANON_KEY: '${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''}'
};

// Validation: Check if environment variables were properly set
if (!window.ENV.SUPABASE_URL || !window.ENV.SUPABASE_ANON_KEY) {
  console.error('❌ Supabase environment variables not configured!');
  console.error('Please add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to your Vercel project settings.');
  console.error('See SUPABASE_SETUP.md for instructions.');
}
`;

fs.writeFileSync('config.js', config);
console.log('✅ config.js generated successfully');
